version: 2

# MkDocs configuration settings
mkdocs:
  configuration: mkdocs.yml  # Path to your MkDocs config file

# Python environment settings
python:
  version: "3.12"  # Specify the Python version
  install:
    - requirements: requirements.txt  # Install dependencies from requirements.txt
    - pip: mkdocs  # Install MkDocs using pip (this should be in a dictionary)

# Build settings
build:
  os: ubuntu-22.04  # Operating system (default Ubuntu should work fine)

  # Define the command to build your documentation
  commands:
    - mkdocs build --clean  # This command tells Read the Docs how to build the site
