version: 2


mkdocs:
  configuration: mkdocs.yml  

python:
  version: "3.12"
  install:
    - requirements: requirements.txt
    - pip install mkdocs

build:
  os: ubuntu-22.04


  commands:
    - mkdocs build --clean 