version: 2


mkdocs:
  configuration: mkdocs.yml  

python:
  install:
    - requirements: requirements.txt  

build:
  os: ubuntu-22.04  
  tools:
    mkdocs:
      version: "1.6.1"


  commands:
    - mkdocs build --clean 